### ISSUE TITLE
Application hangs when selecting audio interface twice

### ISSUE THREAD

**Issue by shinohara-rin** [nekomeowww/sobani#11]
Applications hangs on MacOS 10.14.6.

Steps to reproduce the issue:
1. Select an audio interface.
2. Select an audio interface again.
3. Applications hangs.

**Comment by nekomeowww** [comment]
This is a known issue due to incorrect usage of the macOS interface api port

**Comment by BlueCocoa** [comment]
Thanks for your reporting, experiencing same issue now. 
Will dig into it/

**Comment by BlueCocoa** [comment]
This commit [245d884](https://github.com/nekomeowww/sobani/commit/245d8845ab5f1335101501414dc834d1b76a8dbc) resolved this issue. 
The reason that the issue occurred is that the audio device instance was checked for `null` **and** `started`. However, it is not necessary to check whether if the device was `started`.
