### ISSUE TITLE
Linux 運行異常

### ISSUE THREAD

**Issue by KagurazakaIzumi** [nekomeowww/sobani#12]
Arch Linux self build, can’t get Share ID
- Kernel Version : Linux 5.6.2-arch1-2   

Ubuntu run release AppImage , can’t open
- Kernel Version : Linux 5.4.0-21-generic
- Release Version : Ubuntu Focal Fossa (Development blanch) x86_64
- Error:libportaudio.so.2

**Comment by KagurazakaIzumi** [comment]
Ubuntu issue from VMware issue now closed 
Arch Linux issue solved

**Comment by nekomeowww** [comment]
Issue close due to VMware's audio drive is not capable and working properly on Ubuntu.

**Comment by BlueCocoa** [comment]
This commit [697884b](https://github.com/nekomeowww/sobani/commit/697884b2a4baf85b14716ca51fb4b8550de1967e) resolved this issue. 
The reason that the issue occurred is that the local UDP server received announce response and tried to update the UI before user interface getting ready.
